version: "3"

services: 
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456

    volumes:
      - /data/PostgreSQL:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: postgres_adminer
    restart: always
    ports:
      - 8080:8080