version: "3"

services: 
  db:
    image: postgres
    container_name: postgres_db
    restart: always
    
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 123456

    volumes:
      - /data/PostgreSQL/db:/var/lib/postgresql/data

  pgadmin:
    build:
      context: .  
      dockerfile: Dockerfile
    container_name: postgres_pgadmin
    restart: always

    environment: 
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 123456
      PGADMIN_LISTEN_ADDRESS: 
    
    ports: 
      - 8080:80
    
    volumes:
      - /data/PostgreSQL/pgamin:/var/lib/pgadmin
    
