version: "3"

services: 
    supernode:
        build:
            context: .
            dockerfile: Dockerfile
        restart: always
        ports:
            - 5000:5000/udp
            - 5001:5001/udp
