FROM ubuntu:16.04

RUN apt update \
    && apt install net-tools -y \
    && apt install openjdk-8-jdk -y \
    && java -version \
    && apt-get clean

ENV PATH=$PATH:/home/karaf-0.8.4/bin
WORKDIR /home/karaf-0.8.4

EXPOSE 8181 6653 6633
